### ISSUE TITLE
support for Arabic, Persian and other RTL languages

### ISSUE THREAD

**Issue by shuaibzahda** [norman/friendly_id#1015]
As of now, it is possible to use friendly_id with RTL languages but the slug will be more of hashid style which is not really that great for SEO.

Why not support languages like arabic, persian and urdu and hebrew?

**Comment by parndt** [comment]
Sorry for the delay; `friendly_id` doesn't do character-set handling or transliteration itself, it delegates that entirely to https://github.com/norman/babosa

**Comment by parndt** [comment]
Sorry,I was wrong. Friendly ID doesn't currently delegate to Babosa, not since 2012.. actually we call ActiveSupport's parameterize which transliterates according to its rules. 

That's why you were seeing hashid-style slugs. Arabic, Persian, Urdu and Hebrew have no transliteration rule, so `parameterize` returns an empty string, and FriendlyId falls back to a UUID because it has nothing else to work with:

```ruby
"مرحبا بالعالم".parameterize   #=> ""
```

The good news is that those rules are yours to define. Add one for your locale and it works:

```yaml
# config/locales/ar.yml
ar:
  i18n:
    transliterate:
      rule:
        م: "m"
        ر: "r"
        ح: "h"
        # ...and so on
```

```ruby
I18n.locale = :ar
"مرحبا بالعالم".parameterize   #=> "mrhba-balealm"
```

You can also skip I18n entirely and override `normalize_friendly_id` in your model, if you'd rather.
