### ISSUE TITLE
Validation error localization: "Friendly is reserved"

### ISSUE THREAD

**Issue by vfonic** [norman/friendly_id#664]
Hi, I've just tried out friendly_id for the first time and it's an awesome gem.

I have some issue when creating new account with reserved word like 'admin'. After the validation fails, I get the error message "Friendly is reserved". I'm looking in the ways of customizing and localizing this string. How can I achieve that?

**Comment by parndt** [comment]
Under the hood we use [validates_exclusion_of](http://api.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html#method-i-validates_exclusion_of) which should mean that you can override the message with a locale file, i.e. `config/locales/en.yml` for English, like this: http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

Haven't done it, so don't know the exact nesting but I hope this helps.

**Comment by vfonic** [comment]
Thanks @parndt! I've found which message to override:
`activerecord.errors.messages.exclusion` or even better `activerecord.errors.models.user.attributes.friendly_id.exclusion` then it doesn't override other exclusion validation messages.

What I initially tried to do, and still didn't succeed, is to display this message when friendly_id validation fails: "Username already taken" as that message makes more sense to me to display to user (instead of "Friendly is reserved").

So far I've come to the part where "is reserved" is *translated* to "is already taken". I guess this is a translation question now, but if you have any ideas on how to translate "Friendly", please do share. I've tried every possible option I could think of.

**Comment by norman** [comment]
This works for me.

```yaml
es:
  activerecord:
    errors:
      models:
        book:
          attributes:
            friendly_id:
              exclusion: 'no está disponible'

    models:
      book: Libro
    attributes:
      book:
        title: título
        author: autor
        slug: identificador amigable
        friendly_id: identificador amigable
```

**Comment by vfonic** [comment]
Thanks @norman! That works!

Here's the shorter version that also seems to work:
```
en:
  activerecord:
    errors:
      models:
        user:
          attributes:
            friendly_id:
              exclusion: already taken
    attributes:
      user:
        friendly_id: Username
```
